models/Literature.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for collection "literature".
 *
 * @property \MongoDB\BSON\ObjectID|string $_id
 * @property string $title
 * @property string $keyword
 * @property string $language
 * @property integer $category_id
 * @property integer $year
 * @property string $abstract
 * @property integer $author_id
 * @property integer $academic_supervisor
 * @property integer $main_supervisor
 * @property integer $co_supervisor
 * @property string $type
 * @property string $summary
 * @property string $konten
 * @property string $citation
 * @property string $data_source
 * @property string $file
 * @property string $referral_id
 * @property datetime $create_time
 * @property datetime $update_time
 * @property string $status
 */
class Literature extends \yii\mongodb\ActiveRecord
{
    public $keywords_text;
    public $category;
    public $author;
    public $caption;
    public $test_method;
    public $keyword_tags;
    private $_oldKeyword;

    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return 'literature';
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        return [
            '_id',
            "id_usulan" ,
            "author_id",
            "tahun_usulan",
            "id_kegiatan" ,
            "tahun_kegiatan",
            "judul" ,
            "pengarang",
            "file" ,
            "kategori_sbk" ,
            "kd_program_hibah",
            "bidang_fokus" ,
            "keyword",
            "abstrak" ,
            "konten" ,
            "pendahuluan",
            "latar_belakang",
            "tinjauan_pustaka",
            "tujuan",
            "metode" ,
            "status",
            "solusi_permasalahan",
            "gambaran_iptek" ,
            "daftar_pustaka" ,
            "data_source" ,
            "plagiarism_check_status",
            "plagiarism_check_time" ,
            "create_user",
            "create_time",
            "update_user",
            "update_time",
            "jenis_kegiatan",
            "plagiarism_result",
            "pembanding"
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'judul', 'tahun_usulan','tahun_kegiatan','keyword'           ,
            'pengarang' ,'abstrak' ,'kd_program_hibah'],'required'],
            [['id_usulan',
            'author_id',
            'id_kegiatan',
            'judul'     ,
            'tahun_usulan',
            'tahun_kegiatan',
            'keyword'           ,
            'pengarang'  ,
            'konten'  ,
            'abstrak'            ,
            'pendahuluan'        ,
            'latar_belakang'      ,
            'tinjauan_pustaka'    ,
            'tujuan'             ,
            'kategori_sbk' ,
            'kd_program_hibah',
            'bidang_fokus'     ,
            'metode'             ,
            'status',
            'solusi_permasalahan' ,
            'gambaran_iptek'      ,
            'daftar_pustaka','jenis_kegiatan',
            "data_source" ,
            "plagiarism_check_status",
            "plagiarism_check_time" ,
            "create_user",
            "create_time",
            "update_user",
            "update_time","plagiarism_result",'pembanding'], 'safe'],
            [['id_usulan', 'id_kegiatan'], 'unique', 'targetAttribute' => ['id_usulan', 'id_kegiatan'], 'message' => 'Kombinasi ID Usulan & ID Kegiatan sudah pernah di input'],
            ['file', 'required', 'on' => 'create'],
            ['file', 'file', 'extensions' => 'pdf', 'maxSize' => 50000 * 1024, 'tooBig' => 'Limit is 50 MB'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            '_id' => 'ID',
            "id_usulan" => 'ID Usulan',
            "tahun_usulan"=> 'Tahun usulan',
            "id_kegiatan" => 'ID Kegiatan',
            "tahun_kegiatan"=> 'Tahun kegiatan',
            "judul" => 'Judul',
            "pengarang"=> 'Pengarang',
            "file" => 'File',
            "kategori_sbk" => 'Kategori sbk',
            "kd_program_hibah"=> 'Kode program hibah',
            "bidang_fokus" => 'Bidang fokus',
            "keyword"=> 'Keyword',
            "abstrak" => 'Abstrak',
            "konten" => 'Konten',
            "pendahuluan"=> 'Pendahuluan',
            "latar_belakang"=> 'Latar belakang',
            "tinjauan_pustaka"=> 'Tinjauan pustaka',
            "tujuan"=> 'tujuan',
            "metode" => 'Metode',
            "solusi_permasalahan"=> 'Solusi permasalahan',
            "gambaran_iptek" => 'Gambaran iptek',
            "daftar_pustaka" => 'Daftar pustaka',
            "data_source" => 'Data source',
            "plagiarism_check_status"=> 'Status',
            "plagiarism_check_time" => 'Plagiarism check time',
            "create_user"=> 'Create user',
            "create_time"=> 'Create time',
            "update_user"=> 'Update user',
            "update_time"=> 'Update time',
        ];
    }


    public function afterFind() {
        $this->author= User::findOne($this->author_id);
        $keyword_tags = '';
        foreach (explode(',', $this->keyword) as $keyword) {
            $keyword_tags .= '<span class="label label-info">' . trim($keyword) . '</span> ';
        }
        $this->keyword_tags = $keyword_tags;
        $this->_oldKeyword = $this->keyword;
    }



    public function beforeSave($insert) {
        parent::beforeSave($insert);
        if ($insert) {
            $this->create_time = date('Y-m-d h:i:s');
        } else {
            $this->update_time = date('Y-m-d h:i:s');
        }


        return true;
    }

    /**
     * This is invoked after the record is deleted.
     */
    public function afterDelete() {
        parent::afterDelete();
        $s=  explode(',', $this->keyword);
        foreach($s as $d){
            $key = Keyword::findOne(['name'=>$d]);
            if($key){
            $key->frequency=$key->frequency -1;
            $key->save();
            }
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProgramHibah()
    {
        return ProgramHibah::findOne(['kode_program_hibah' =>  "$this->kd_program_hibah"]);
    }

    public function afterSave($insert, $changedAttributes) {
        parent::afterSave($insert, $changedAttributes);
        // Keyword::updateFrequency($this->keyword);
        
        return true;
    }
    
    public function getPlagiarismTest()
    {
        $data=PlagiarismTest::find()->where(['document_id' => (string)$this->_id])->orderBy("datetime desc")->one();
        return $data;
    }
}

controllers/LiteratureController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Literature;
use app\models\LiteratureSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Asset;
use app\models\Keyword;
use Da\QrCode\QrCode;
use app\models\PlagiarismTest;
use app\models\PlagiarismCompare;
use keltstr\simplehtmldom\SimpleHTMLDom;
use yii\base\ErrorException;
use yii\mongodb\Query;
use yii\httpclient\Client;
use yii\helpers\Json;

/**
 * LiteratureController implements the CRUD actions for Literature model.
 */
class LiteratureController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Literature models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new LiteratureSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(["create_time"=> SORT_DESC]);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Literature model.
     * @param integer $_id
     * @return mixed
     */
    public function actionGet($id) {
        $model = Asset::findOne($id);
        header('Content-type: ' . $model->contentType);
        echo $model->file->getBytes();
    }

    public function actionView($id) {

        $asset = Asset::findOne(['literature_id' => $id]);
        $model=$this->findModel($id);
        return $this->render('view', [
                    'model' => $model,
                    'asset' => $asset,
        ]);
    }

    public function actionKeywordSearch($q = null) {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $querys = Keyword::find()->select(['name'])
                    ->where(['like', 'name', $q])
                    ->limit(20)
                    ->all();
            $data = array();
            foreach ($querys as $query) {
                $data['id'] = $query->name;
                $data['text'] = $query->name;
            }

            $out['results'] = [$data];
//        } elseif ($id > 0) {
//            $out['results'] = ['id' => $id, 'text' => Keyword::find($id)->name];
        }
        return $out;
    }

    function pdftotext($file) {
        try {
            $content = shell_exec(Yii::getAlias('@bin') . Yii::$app->params['pdfBin'] . '/pdftotext -nopgbrk -q -layout "' . $file . '" -');
            return utf8_encode($content);
        } catch (Exception $e) {
            return 'ERROR:' . $e->getMessage();
        }
    }

    public function actionPlagiarismCertificate($id) {
        return $this->render('certificate', [
                    'model' => $this->findModel($id),
        ]);
    }

    public function actionFile($id) {
        $asset = Asset::findOne(['literature_id' => $id]);
        return $this->renderAjax('_file', [
                    'model' => $this->findModel($id),
                    'asset' => $asset,
        ]);
    }

    public function actionPlagiarismResult($id) {
        $test=  PlagiarismTest::findOne($id);
        $model= $this->findModel($test->document_id);
        if ($model->load(Yii::$app->request->post()) and $model->save()) {
            Yii::$app->session->setFlash('success', 'Status Saved');
        }
        return $this->render('result', [
                    'model' => $model,
                    'test' => $test,
        ]);
    }

    public function actionCreatePembanding() {
        $model = new Literature();
        $model->scenario = 'create';
        if ($model->load(Yii::$app->request->post())) {
            $file = \yii\web\UploadedFile::getInstance($model, 'file');
            //            var_dump($file);exit();
            $file->saveAs(Yii::getAlias('@webroot') . '/uploads/' . $file);
            $filepath = Yii::getAlias('@webroot') . '/uploads/' . $file;
            $content = $this->pdftotext($filepath);
            if ($content == '' || substr($content, 0, 5) == 'ERROR') {
                Yii::$app->getSession()->setFlash('danger', '<strong>Oopss, something went wrong when extracting your document, please see help page for further information!</strong>');
                throw new \yii\web\HttpException(405);
            } else {
                $model->konten = $content;
            }
            $model->pembanding = "Y";
            $model->file = $file->name;
            $model->author_id = Yii::$app->user->identity->id;
            $model->plagiarism_check_status = 'Submit';
            $model->keyword = $model->keyword != null ? implode(',', $model->keyword) : '';
            $programHibah=\app\models\ProgramHibah::findOne(['kode_program_hibah' =>  $model->kd_program_hibah]);
            $model->jenis_kegiatan=$programHibah?$programHibah->jenis_kegiatan:"";
            // var_dump($model->jenis_kegiatan);exit;
            $model->save();
            //            var_dump($model->getErrors());exit();
            if (!$model->getErrors()) {
                $id=(string) $model->_id;
                $asset = new Asset();
                $asset->literature_id = $id;
                $asset->adhoc_id = '';
                $asset->file = $filepath;
                $asset->contentType = $file->type;
                $asset->filename = $file->name;
                $asset->uploadDate = date('Y-m-d h:i:s');
                $asset->save();
                unlink(Yii::getAlias('@webroot') . '/uploads/' . $file);

                Yii::$app->getSession()->setFlash('success', 'Data Saved');
                return $this->redirect(['create-pembanding']);
            }else{
                Yii::$app->getSession()->setFlash('danger', '<strong>Oopss, something went wrong when extracting your document, please see help page for further information!</strong>');
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionCreate() {
        $model = new Literature();
        $model->scenario = 'create';
        if ($model->load(Yii::$app->request->post())) {
            $file = \yii\web\UploadedFile::getInstance($model, 'file');
            //            var_dump($file);exit();
            $file->saveAs(Yii::getAlias('@webroot') . '/uploads/' . $file);
            $filepath = Yii::getAlias('@webroot') . '/uploads/' . $file;
            $content = $this->pdftotext($filepath);
            if ($content == '' || substr($content, 0, 5) == 'ERROR') {
                Yii::$app->getSession()->setFlash('danger', '<strong>Oopss, something went wrong when extracting your document, please see help page for further information!</strong>');
                throw new \yii\web\HttpException(405);
            } else {
                $model->konten = $content;
            }
            $model->pembanding = "N";
            $model->file = $file->name;
            $model->author_id = Yii::$app->user->identity->id;
            $model->plagiarism_check_status = 'Submit';
            $model->keyword = $model->keyword != null ? implode(',', $model->keyword) : '';
            $programHibah=\app\models\ProgramHibah::findOne(['kode_program_hibah' =>  $model->kd_program_hibah]);
            $model->jenis_kegiatan=$programHibah?$programHibah->jenis_kegiatan:"";
            // var_dump($model->jenis_kegiatan);exit;
            $model->save();
            //            var_dump($model->getErrors());exit();
            if (!$model->getErrors()) {
                $id=(string) $model->_id;
                $asset = new Asset();
                $asset->literature_id = $id;
                $asset->adhoc_id = '';
                $asset->file = $filepath;
                $asset->contentType = $file->type;
                $asset->filename = $file->name;
                $asset->uploadDate = date('Y-m-d h:i:s');
                $asset->save();
                unlink(Yii::getAlias('@webroot') . '/uploads/' . $file);

                return $this->redirect(['plagiarism-test/create', 'id' => (string) $model->_id]);
                // return $this->redirect(['index']);
            }else{
                Yii::$app->getSession()->setFlash('danger', '<strong>Oopss, something went wrong when extracting your document, please see help page for further information!</strong>');
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionProcess($id) {
        $model = $this->findModel($id);
        $model->plagiarism_check_status="Processing";
        $model->save();
        return $this->redirect(['index']);
    }

    /**
     * Updates an existing Literature model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $asset = Asset::findOne(['literature_id' => $id]);
        $s = explode(',', $model->keyword);
        foreach ($s as $d) {
            $data[] = $d;
        }
        $model->keyword = $data;
        if ($model->load(Yii::$app->request->post())) {
            $file = \yii\web\UploadedFile::getInstance($model, 'file');
            //            var_dump($file);exit();
            if($file){

views/literature/_file.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Literature */

$this->title = $model->judul;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Literatures'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="literature-view">

    <?php if(strpos($asset->contentType,'image')===false): //Not an image?>
        <iframe src="<?=Url::to(['literature/get', 'id'=>(string)$asset->_id]);?>" width="100%" height="600px"></iframe>
    <?php else: ?>
        <?= Html::img(Url::to(['literature/get', 'id'=>(string)$asset->_id]), ['alt'=>$asset->description]);?>
    <?php endif; ?>

</div>

views/literature/_filter.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use filsh\yii2\readmore\Readmore;

$value= \app\models\Params::findOne(['name'=>'Minimum Result'])->value;
$search = "$(document).ready(function(){
    $('#modal-status').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var modal = $(this)
        var title = button.data('title') 
        var href = button.attr('href') 
        modal.find('.modal-title').html(title)
        modal.find('.modal-body').html('<i class=\"fa fa-spinner fa-spin\"></i>')
        $.post(href)
            .done(function( data ) {
                modal.find('.modal-body').html(data)
            });
        });
            
});";
$this->registerJs($search);
?>
<?php
Modal::begin([
    'id' => 'modal-status',
    'header' => '<h4 class="modal-title"></h4>',
    'headerOptions'=>['style'=>'background-color: #8A2BE2; height:50px;color:white;'],
    'options'=>['height'=>'800px', 'tabindex' => false,],
]);

echo '...';

Modal::end();
?>
<div class="row">
    <div class="col-md-12">

        <!-- About Me Box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Candidates For Analysis</h3>
                <div class="box-body table-responsive">
                    <table class="table table-hover">

                        <tbody><tr bgcolor="whitesmoke">
                                <th style="text-align: center">Check to compare<br><input type='checkbox' name='checkall' onclick='ToggleAll(this);' checked="checked"></th>
                                <th style="text-align: center">Candidate Rank</th>
                                <!--<th>DB ID</th>-->
                                <th >Source</th>
                                <th >Url/Snippet</th>
                                <th style="text-align: center">Similarity Percentage</th>
                                <th style="text-align: center">Similarity <br>(>= <?= $value;?>%)</th>
                                <th style="text-align: center">Detail</th>

                            </tr>
                            <?php $i =1;$no=0;
                            foreach ($results as $result) {?>
                                <tr>
                                    <td style="text-align: center"><input type="checkbox" name="items[]" class="grup" value="<?= (string)$result->_id?>" checked="checked"></td>
                                    <td style="text-align: center"><b>#<?= $i++; ?><b></td>
                                    <td><?= $result->source?></td>
                                    <td><?php if($result->source=='Online sources'){ ?>
                                        <a href="<?= $result->url;?>" target="_blank"><?= $result->formatedurl;?></a>
                                    <?php }else{
                                         echo $result->url;
                                        }
                                         echo '<br><br>';
                                        ?>
                                        <?php
                                            Readmore::begin();
                                            echo $result->snippet;
                                            Readmore::end()
                                         ?>
                                    </td>
                                    <td style="text-align: right"><div id="sim<?= (string)$result->_id;?>"></div></td>
                                    <td style="text-align: center">
                                        <div id="cek<?= (string)$result->_id;?>">
                                        </div>
                                        <div style='display:none;' id="suk<?= (string)$result->_id;?>">
                                            <i style='color:green' class='fa fa-check fa-2x'></i>
                                        </div>
                                        <div style='display:none;' id="gag<?= (string)$result->_id;?>">
                                            <i style='color:red' class='fa fa-times fa-2x'></i>
                                        </div>
                                    </td>
                                    <td style="text-align: center">
                                        <div style='display:none;' id="modal<?= (string)$result->_id;?>">
                                             <?= Html::a('Upload Manual', ['plagiarism-test/upload-manual','id'=>(string)$result->_id], 
                                                [
                                                    'class' => 'btn btn-block btn-primary btn-flat btn-xs',
                                                    'data-toggle' => "modal",
                                                    'data-target' => "#modal-status",
                                                    'data-title' => Yii::t('app', 'Upload manual content'),
                                                ]);
                                                ?> 
                                        </div>    
                                    <div style='display:none;' id="vew<?= (string)$result->_id;?>"><?= Html::a('View', Url::toRoute(['/plagiarism-compare/view', 'id' => (string)$result->_id]), [
                                    'target' => '_blank',
                                    'title' => Yii::t('yii', 'View'),
                                    'class' => 'btn btn-block btn-default btn-flat btn-xs',
                                    ]); ?></div></td>

                                </tr>
                            <?php $no++;} ?>


                        </tbody></table>
                </div>
            </div>

        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->

</div>

views/literature/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LiteratureSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="literature-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, '_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'keywords') ?>

    <?= $form->field($model, 'language') ?>

    <?= $form->field($model, 'category_id') ?>

    <?php // echo $form->field($model, 'year') ?>

    <?php // echo $form->field($model, 'abstract') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <?php // echo $form->field($model, 'academic_supervisor') ?>

    <?php // echo $form->field($model, 'main_supervisor') ?>

    <?php // echo $form->field($model, 'co_supervisor') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'summary') ?>

    <?php // echo $form->field($model, 'content') ?>

    <?php // echo $form->field($model, 'citation') ?>

    <?php // echo $form->field($model, 'data_source') ?>

    <?php // echo $form->field($model, 'file') ?>

    <?php // echo $form->field($model, 'referral_id') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'update_time') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/literature/_view.php
<?php

use yii\helpers\Html;
use filsh\yii2\readmore\Readmore;
use yii\bootstrap\Modal;
?>
<div class="row">
    <div class="col-md-12">

        <!-- About Me Box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">About Literature</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="col-md-6">
                    <strong><i class="fa fa-book margin-r-5"></i> Pengarang</strong>
                 
                    <p class="text-muted">
<?= $model->pengarang; ?>
                    </p>
                    <strong><i class="fa fa-book margin-r-5"></i> Judul</strong>

                    <p class="text-muted">
<?= $model->judul; ?>
                    </p>
                    <!--<hr>-->
                    <strong><i class="fa fa-tags margin-r-5"></i> Kata Kunci</strong>

                    <p>
<?= $model->keyword_tags; ?>

                    </p>
                    <!--<hr>-->

                    <strong><i class="fa fa-tags margin-r-5"></i> Abstrak</strong>

                    <p><?php
                        Readmore::begin();
                        echo $model->abstrak;
                        Readmore::end()
                        ?></p>
                    <?php
//                    $file_url = Yii::$app->request->hostInfo. '/uploads/' . $model->file;
//                    $file_location = Yii::$app->basePath. '/web/uploads/' . $model->file;
//                    if (file_exists($file_location)) {
                        ?>

                       

                         <?php $asset = \app\models\Asset::findOne(['literature_id' => (string)$model->_id]); 
                        if($asset){
                        ?>
                         <strong><i class="fa fa-file-pdf-o margin-r-5"></i> File</strong>
                        <p><?= Html::a('Show file', ['literature/file','id'=>(string)$model->_id], ['class' => 'btn btn-primary btn-sm btn-danger','target'=>'_blank']);?> </p>
                        <?php } ?>

                    <?php //  } ?>
                </div>

                <!-- <div class="col-md-6">
                  
                    <strong><i class="fa fa-flag margin-r-5"></i> Language</strong>

                    <p class="text-muted">
<?php //$model->language; ?>
                    </p> -->

                    <!--<hr>-->

                    <strong><i class="fa fa-calendar margin-r-5"></i> Tahun Usulan</strong>

                    <p class="text-muted">
                    <?= $model->tahun_usulan; ?>
                    </p>
                    <strong><i class="fa fa-calendar margin-r-5"></i> Tahun Kegiatan</strong>

                    <p class="text-muted">
                    <?= $model->tahun_kegiatan; ?>
                    </p>

                    <strong><i class="fa fa-tags margin-r-5"></i> Kategori SBK</strong>
                    <p><?php   echo $model->kategori_sbk;  ?></p>
                    <strong><i class="fa fa-tags margin-r-5"></i> Program Hibah</strong>
                    <p><?php   echo $model->programHibah->nama;  ?></p>
                    <strong><i class="fa fa-tags margin-r-5"></i> Jenis Kegiatan</strong>
                    <p><?php   echo $model->jenis_kegiatan;  ?></p>
                </div>

                <?php
//                        Modal::begin([
//                            'id' => 'modal-tester',
//                            'header' => '<h4 class="modal-title">Content</h4>',
//                            'size' => Modal::SIZE_LARGE,
//                            'options' => ['height' => '600px'],
//                            'toggleButton' => ['label' => '<i class="icon fa fa-book"></i> View Content', 'class' => 'btn btn-primary'],
//                        ]);
//
//                        echo $model->content;
//
//                        Modal::end();
                ?>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->

</div>

views/literature/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Literature */

$this->title = Yii::t('app', 'Submit Literature');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Literatures'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="literature-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/literature/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Literature */

$this->title = Yii::t('app', 'Update {modelClass} ', [
    'modelClass' => 'Literature',
]) ;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Literatures'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->author->name , 'url' => ['view', 'id' => (string)$model->_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="literature-update">

    <?= $this->render('_form', [
        'model' => $model,
        'asset' => $asset,
    ]) ?>

</div>

views/literature/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\dialog\Dialog;

/* @var $this yii\web\View */
/* @var $model app\models\Literature */

$this->title = 'View for Literature';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Literatures'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->author->name , 'url' => ['view', 'id' => (string) $model->_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Detail');
echo Dialog::widget();
?>
<div class="literature-view">

    <p>
    <?php if (Yii::$app->user->identity->role == 'Applicant') {?>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => (string) $model->_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => (string) $model->_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    <?php } ?>
    </p>
    
<?= $this->render('_view', ['model' => $model]) ?>
</div>